/**
 * Example of 
 * - reading a newline-delimited text file into a plain-old JSON Object (PODO) array
 * - and writing it back to 'tmpData.js' as a Javascript file
 */
import fs from 'fs'
import { file2JsonArray } from './file2JsonArray.js'

const progName = 'runFile2JsonArray.js'
const inputName = (process.argv.length > 2) ? process.argv[2] : 'Trees.txt'
const outputName = (process.argv.length > 3) ? process.argv[3] : 'Trees.js'
const varName = (process.argv.length > 4) ? process.argv[4] : 'trees'
if (process.argv.length < 3) {
    console.log(`*** USAGE: node ${progName} <inputFileName> [<outputFileName>]`)
}
console.log(`Reading file '${inputName}' and writing file '${outputName}'...\n`)

// Read the local text file into a Javascript array
const textArray = await file2JsonArray(inputName)
console.log(`File '${inputName}' has ${textArray.length} lines:`)
console.log(textArray)

// Create some Javascript from the text array
let js = `// auto-generated by toJsonFile.js on ${new Date().toLocaleString()}\n`
js += `export const ${varName} = ${JSON.stringify(textArray, null, 2)}\n`
console.log(js)

// Write the Javascript to a file for later use
fs.writeFile(outputName, js, function (err) {
    if (err) throw err
    console.log(`Data written to ${outputName}'`)
})
